name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image Step
        run: |
          docker version
          docker compose version
          docker compose run --rm web echo "Installing gems and node modules"
          docker compose up -d
          docker ps

      - name: Rubocop Standard
        run: docker compose exec web standardrb

      - name: Run Sorbet
        run: docker compose exec web srb

      - name: Test setup
        run: |
          docker compose exec web bundle exec rails db:create RAILS_ENV=test
          docker compose exec web bundle exec rails db:schema:load RAILS_ENV=test

      - name: Run tests
        run: docker compose exec web bundle exec rails test
